name: Renovate

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"

permissions: {}

jobs:
  renovate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-renovate.yml@9c699818ddf1043b8f5af8b862f59f783c6c7bda # v1
    secrets:
      renovate_token: ${{ secrets.RENOVATE_TOKEN }}
