name: Validate Renovate Config

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"

permissions:
  {}

jobs:
  validate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-validate-renovate.yml@4d3b97eb9760539d2b4a8f2a495db0ec3bf9e8a0 # v1
